### ISSUE TITLE
When deleting a gallery, it's associated gallery term doesn't get deleted

### ISSUE THREAD

**Issue by jcowher** [bendoh/WP-Remember-The-Galleries#8]
When you delete a gallery post, it's associated gallery term doesn't get removed from the database. This is normal WP behavior due to terms normally having a 1 to many relationship, but in the case of galleries, terms are a 1 to 1 relationship, so we should probably make sure these terms also get removed to avoid cluttering up the wp_terms table.

**Comment by balbuf** [comment]
This is fixed as of #17.
